name: Build and Publish Frontend Image

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

env:
  BUILD_PATH: "apps/frontend"

jobs:
  build_and_publish_frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.BUILD_PATH }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Set up pnpm store path
        run: pnpm config set store-dir ../../.pnpm-store

      - name: Ensure pnpm store directory exists
        run: mkdir -p ../../.pnpm-store

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: |
            ../../.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('apps/frontend/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.BUILD_PATH }}
          file: ${{ env.BUILD_PATH }}/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          build-args: |
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
            GITHUB_SHA=${{ github.sha }}
            GITHUB_REF=${{ github.ref }}
            GITHUB_WORKFLOW=${{ github.workflow }}
            GITHUB_ACTOR=${{ github.actor }}
